name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Find JAR files
        id: find_jars
        run: |
          echo "jar_files=$(find build/libs -name "*.jar" -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_jars.outputs.jar_files }}
          name: "Release ${{ github.ref_name }}"
          body: "Automatic release"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
